### ISSUE TITLE
Reference tab: button for deleting files is missing

### ISSUE THREAD

**Issue by sihui62** [opensmarthouse/opensmarthouse-web#1]
On the Reference tab a button for deleting files is missing.

![grafik](https://user-images.githubusercontent.com/10405486/88476686-c053ed80-cf3a-11ea-832f-6a6e16033412.png)

**Comment by cdjackson** [comment]
Should be working now - admin only function -:

![image](https://user-images.githubusercontent.com/1041475/88478845-4e33d680-cf43-11ea-8706-37e9b2d91a38.png)

**Comment by cdjackson** [comment]
Note that if you try and delete a file in the database right now it will fail as there are no files - upload a file, then you can delete it :)

**Comment by sihui62** [comment]
Thx, deleting files is working now.

**Comment by cdjackson** [comment]
Thanks.
