### ISSUE TITLE
Return to previous page after login

### ISSUE THREAD

**Issue by 5iver** [opensmarthouse/opensmarthouse-web#12]
When you go to the site to quickly look something up and are viewing a device, if you decide to login to make a change, you go to the home screen. It would be very nice to go back to the device you were viewing after logging in.

**Comment by bwosborne2** [comment]
I second that idea 👍

**Comment by cdjackson** [comment]
I fully agree - it's just not simple as it seemed. I spent some time looking at different options this afternoon, but didn't find a simple, reliable method yet.  You'd think this would be super simple!

**Comment by bwosborne2** [comment]
Would this help?
https://perishablepress.com/go-back-via-javascript-and-php/
I know I have a "back button" createdand in production. I can check later what I used after I return to work.

**Comment by cdjackson** [comment]
I tried various incarnations of the “back” command, but couldn’t get it to work. Some of this may be related to Wappler running js on completion of the login api so I might try and abstract this away.

**Comment by cdjackson** [comment]
Yes, the issue was I couldn’t run JS direct in the Wappler event, but adding a level of abstraction made it work.

**Comment by bwosborne2** [comment]
Here is what I use on a page. I stripped out my css styling

`<button id="backbutton" type="button" onclick="location.href='javascript:history.back();';">Back</button>`

**Comment by cdjackson** [comment]
As mentioned - the issue was just with the way that Wappler called the javasctipt and I had to add a level of abstraction to sort it.

Do I assume that it's still not working Bruce?

**Comment by bwosborne2** [comment]
I do not know. I promised sharing my solution after I returned to work. I did not think it was a solution I posted in the links.

**Comment by cdjackson** [comment]
@bwosborne2 I just re-checked it here, and it was working fine on both Chrome and Safari and it's working fine for me. Maybe it's a browser issue - what browser are you using.

**Comment by cdjackson** [comment]
> I promised sharing my solution after I returned to work.

Ah - ok. So it's working ok though?

**Comment by bwosborne2** [comment]
I have not checked.

**Comment by 5iver** [comment]
I just went to a device, logged in, and I went back to the device page using FF.

**Comment by cdjackson** [comment]
Thanks Scott - ok, so I think this looks like it's working ok then so I'll close this.
