### ISSUE TITLE
Text after registration has typos and is confusing

### ISSUE THREAD

**Issue by liko9** [opensmarthouse/opensmarthouse-web#15]
The text received after successfully clicking on the registration link in email returns with "Thankyou for registering - please enjoy the site. To contact the site administrators through the ticket system."  I know this is "under construction" so maybe this is already scheduled to be changed when the cut-over occurs?

**Comment by cdjackson** [comment]
Hi,
Thanks for the comments. I'm not sure that I understand what you're actually reporting though? Do you mean to remove the "under construction" sign on the front page?  At the moment I'm mainly focussing on the ZWave database - I could update the  front page to say that - is that what you are raising here?

Chris

**Comment by bwosborne2** [comment]
There is a typo missing space in the "Thankyou" message" 🤣 
Grammar is poor too. Should "To contact the site administrators through the ticket system." be

"If you have any issues, please contact the site administrators through the ticket system." ?

**Comment by cdjackson** [comment]
Ah - Ok, so the issue is that the grammar isn't so good - I'll update that.

Is that what you're reporting @liko9 ?

**Comment by bwosborne2** [comment]
Also missing space between "Thank" and "you"

**Comment by cdjackson** [comment]
I've updated it to -:

> Thank you for registering - please enjoy the site. To contact the site administrators, please open a ticket through the ticket system.

**Comment by cdjackson** [comment]
I think this is resolved so I'll close, but if I've misunderstood something, then please clarify.
