### ISSUE TITLE
Configuration Parameter Minimum

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#20]
Configuration Parameter Minimum

If the minimum value is 0 the edit window displays no value for that field. I even set it to 0 and verified.

**Comment by cdjackson** [comment]
I've changed this to a text input, and changed the way it's formatted - it seems to work now. Please keep an eye out for any errors in this area.

**Comment by bwosborne2** [comment]
I assume somewhere you are still check ing for a valid numeric value? Or is any invalid value automatically 0 ? 

For instance, somebody, when copying could inadvertently ass a space, invalidating the value.

**Comment by cdjackson** [comment]
A blank or space is fine - no minimum is perfectly valid.

If there are other issues, then let's open another issue - let's not just keep adding to this which simply talks about.0 not being able to be set.
