### ISSUE TITLE
Device definition contains errors!

### ISSUE THREAD

**Issue by 5iver** [opensmarthouse/opensmarthouse-web#22]
It would be nice if the list of errors were on new lines... maybe bulleted.

![image](https://user-images.githubusercontent.com/21967853/97793628-e1288080-1bc4-11eb-930b-ef9b9b79b921.png)

**Comment by cdjackson** [comment]
Agreed - when I added this I couldn't get it to format well, and time ran out, so it got left as it was... I'll take another look...

**Comment by cdjackson** [comment]
Ok, sorted...

![image](https://user-images.githubusercontent.com/1041475/97798710-6c832f80-1c20-11eb-8f9f-9198437cefd6.png)
