### ISSUE TITLE
Ticket Update Button

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#25]
Then updating a Ticket, the button needs a "wait" symbol (rotating animation) much like approving a device. That indicates the server process has not locked up.

**Comment by cdjackson** [comment]
Since there are no icons in these buttons, I’ll update the button so it is disable while the action is ongoing - it will effectively provide the same feedback and it prevents the button being pressed twice.

**Comment by bwosborne2** [comment]
LOL when I approved a database entry I noticed the progress icon on two different buttons.

**Comment by cdjackson** [comment]
Yeah - that was a cut and paste error. I forgot about that but will fix it now.

**Comment by bwosborne2** [comment]
I believe this is fixed.
