### ISSUE TITLE
Limit to options "false" does not seem to work

### ISSUE THREAD

**Issue by sihui62** [opensmarthouse/opensmarthouse-web#26]
I did not find an open issue for this problem several users are reporting in the community forum:

The former "free entry" box, now called and extended to "Limit to options" parameter config is not working, so here is a reminder:

https://community.openhab.org/t/configuration-values-for-eurotronic-spirit-z-wave-thermostat-not-writable/107901
https://community.openhab.org/t/openhab-3-0-issues-after-migrating/107887/13

**Comment by bwosborne2** [comment]
Perhaps file an issue in the OH Z-Wave repo?

**Comment by sihui62** [comment]
I think it is related to the database.

**Comment by cdjackson** [comment]
Yes - it's a database issue. The binding doesn't have any knowledge or control of this setting.

**Comment by cdjackson** [comment]
This looks to be fixed now.
