### ISSUE TITLE
OH versions to device detail

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#28]
When browsing a device you can see the first & last approval dates along with OH versions. It would be useful to see that data on a device detail tab. I believe the old site placed it in Reference.

![image](https://user-images.githubusercontent.com/51490785/99902874-dd9d8c00-2c8e-11eb-8a60-59a3ca8916d5.png)

**Comment by cdjackson** [comment]
I'm not really sure I know what you're asking for with this issue @bwosborne2 ?

**Comment by bwosborne2** [comment]
I see now the information is now also on the bottom of the Overview page, 
No issue thanks
