### ISSUE TITLE
Web Lets you create Association Group with 0 nodes

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#32]
Web Lets you create Association Group with 0 nodes
The old site used to error out.

**Comment by cdjackson** [comment]
I've now added a check so there will be an error raised now if someone does this. I've also made this a required field, and can only accept numbers - this should ensure people add something and mostly stop them entering 0. If they do enter 0, then there will be an error and they can't request review.

**Comment by bwosborne2** [comment]
I think this has been resolved.
