### ISSUE TITLE
New User Registration Link

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#33]
I registered a test user with email `bosborne@freeshell.org`. when I first tried logging in I had password issues, so I reset the password & was able to log in with the email address.

I subsequently got an automated email with a link to complete my registration. Of course it errored because the password had been changed,

![image](https://user-images.githubusercontent.com/51490785/105579601-71eea280-5d55-11eb-8a01-de7235c1cfdb.png)

**Comment by cdjackson** [comment]
I’m not sure what the issue is? If you change the password, then the link will probably be invalid since the link is a one way hash using a bunch of information - if you change it, it won’t work - this seems to be what you’ve done? Or do I misunderstand something with this?

**Comment by bwosborne2** [comment]
I received the link to "complete my registration" 6 minutes after the password reset email.

What does completing the registration do?

I created the user only because somebody on the OH forum claimed there was an issue creating a new account.

**Comment by cdjackson** [comment]
It does the same thing as resetting the password. If the mails got delayed, then I can’t really help with that.

It sounds like this is working ok?

**Comment by bwosborne2** [comment]
OK thanks.

BTW, please delete that account. Is has served the purpose of verifying registration.
