### ISSUE TITLE
Faulty SPF record for opensmarthouse.org

### ISSUE THREAD

**Issue by DanielMalmgren** [opensmarthouse/opensmarthouse-web#34]
The SPF record for opensmarthouse.org says  “v=spf1 +ip4:77.68.114.233 +a +mx -all”, but mail from the domain originates at 64.68.202.10 (at least the password reset I tried sending). This makes well configured smtp servers (like mine) completely block mail from the domain.

**Comment by cdjackson** [comment]
I'm not sure what caused this but as far as I can tell there should be no issue at the moment
