### ISSUE TITLE
[zwavedatabase] "Show Diff" is broken.

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#35]
The "Show Diff" function, at tines, gives totally inaccurate data. This is used extensively when reviewing items.  Device 1074 is one obvious example. the device was last approved on 2021-01-16 but then subsequently modified. The diff shows it was created from new.

![image](https://user-images.githubusercontent.com/51490785/106068726-0139e400-60cf-11eb-8af1-1bc28f8cef29.png)

![image](https://user-images.githubusercontent.com/51490785/106068762-16af0e00-60cf-11eb-9f84-d6275f74b224.png)

This is wrapped in the dmx code somewhere so I am inable to assist. Until this is resolved I will refrain from approving anu database Items I did not modify. Once already I depended on the diff and made a ticket only to have to backtrack when the user corrected me.

**Comment by bwosborne2** [comment]
Further research. Looking at the `zwave_devices` table, `approved_export` column is null even though it was approved & exported on `2021-01-16 09:19:23`.
That may point to an approval / export issue

**Comment by bwosborne2** [comment]
When a device is approved, approved data and export date are both set. i thought it strange they looked the same.  Also forst approval data appears empty and does not seem to be referenced in the approval script.

**Comment by cdjackson** [comment]
This was fixed quite a while ago.
