### ISSUE TITLE
[zwavedatabase] openHAB version badges need updating

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#38]
The openHAB version badges were designed to track openHAB 2 version releases.  Currently openHAB 3.0.0 sw recognized and anything newer is SNAPSHOT.

There are now current openHAB 2 and openHAB 3 releases. How should we handle this situation? We could just start tracking openHAB 3.x releases or somehow track both,. perhaps with different colour badges.

**Comment by bwosborne2** [comment]
Self assigning. I have an idea using JSON files for data to make it easier to update.

**Comment by cdjackson** [comment]
Thanks Bruce. I think though that either way - PHP or JSON it's the same? You would need to update a table of versions and dates in a file somewhere :)

The original idea was to have different badges for OH2 and OH3 and also OSH. I did this when OH3 was released, but it got messy as there is limited space so I just kept this a single line for OH for now. It seemed sufficient.

**Comment by bwosborne2** [comment]
I mean a separate file read in by the script so we can change it without having to locate the proper lines in the script. I am considering different coloured badges for both OH2 & OH3, perhaps on a line separate from the date if needed.

I am just trying to be helpful & ease ypur load, not "take over".

**Comment by cdjackson** [comment]
I appreciate the help Bruce - it may slow things down though as it will have to now parse the json file - maybe it's fine - if you want to try it then it's certainly appreciated. The current script is very short to add new versions - it's just the zwaveformatters file - if you add separate badges for OH2 and OH3 you will need to change the formatters file, and also the PHP itself. This is what I did a while back, and as I said it got messy as there is limited space to display multiple tags and I think they scrolled off screen from memory.

**Comment by bwosborne2** [comment]
It can get messy but currently we have both OH2 & OH 3 releases and will have OSH releases too at come time, I hope.

For now I just added 3.0.1 to the list. I also think we should use dates a week before release to insure the accuracy of the badges. Sometimes there is a lag between the last export before the release & the release date itself.

**Comment by cdjackson** [comment]
Sure but this will need to be handled in the code in the first instance. I’m not sure if OH2 will continue to be updated either - it was stated that it wouldn’t be, but this might have changed. I just don’t want this to be an unusable mess as that will be worse than only currently displaying OH2.

**Comment by bwosborne2** [comment]
> Sure but this will need to be handled in the code in the first instance. I’m not sure if OH2 will continue to be updated either - it was stated that it wouldn’t be, but this might have changed. I just don’t want this to be an unusable mess as that will be worse than only currently displaying OH2.


Agreed. Here is Kai's official word. I know 2.5.12 & 3.0.1 were basically released at the same time. Patch Releases are expected well into 2021.

https://community.openhab.org/t/openhab-2-5-x-patch-releases/90248/263

**Comment by bwosborne2** [comment]
Replaces 3.0.1 badge with 2.,5.12 since the updates did not make it to 3.0.1

**Comment by bwosborne2** [comment]
I think we have a reasonable control of this issue for now.
