### ISSUE TITLE
From Address

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#4]
Review Emails **From:** address should be from an **opensmarthouse.org** account, not **cd-jackson.com**.

**Comment by cdjackson** [comment]
I agree - at the moment there's no mail set up for `opensmarthouse.org` so replies would disappear. I'll leave this open and once I get a mailer configured I'll resolve this.

**Comment by cdjackson** [comment]
I think this is done so closing.

**Comment by bwosborne2** [comment]
When receiving review requests From is still `chris@cd-jackson.com`

```
MIME-Version: 1.0
Subject: Database approved
From: ZWave Database <chris@cd-jackson.com>
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
Message-ID: <qj42rd.ijfoo2@www.opensmarthouse.org>
To: BruceOsborne <bwosborne@gmail.com>
Date: Sun,
  1 Nov 2020 09:38:03 +0000 (UTC)
```

**Comment by cdjackson** [comment]
Thanks - I missed that one. If you find more, please note them specifically as this is not set in a single place.
