### ISSUE TITLE
Manufacturers List broken.

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#8]

**Comment by bwosborne2** [comment]
Error
Device definition contains errors!

**Comment by cdjackson** [comment]
Thanks. I forgot to move this when I changed the site. I will look at integrating this on the ZWave admin page.

**Comment by cdjackson** [comment]
I've not copied everything over as yet, but there's now a basic manufacturers list on the zwave database admin page.

**Comment by cdjackson** [comment]
This should now be working
