### ISSUE TITLE
Documentation Processor

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-web#9]
Before the database goes live we need to update the document processor links to the new site.

Before we can do that, the images & manuals need to be uploaded to opensmarthouse.

**Comment by bwosborne2** [comment]
Chris,
Do you want me to make an `OH-Docs` or `OH2-Docs` folder under the repo to start updating the updating the processors? I believe that was supposed to be publicly released.
If so, we probably need a license on this repo first.

**Comment by cdjackson** [comment]
I think all the links are fine now so closing this.
